"""add product variants

Revision ID: b7724ffda64d
Revises: d4ef676f2abd
Create Date: 2026-07-14 16:31:10.707986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7724ffda64d'
down_revision: Union[str, Sequence[str], None] = 'd4ef676f2abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('product_variants', sa.Column('reorder_level', sa.Integer(), nullable=False))
    op.alter_column('product_variants', 'size',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('product_variants', 'barcode',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_variants', 'barcode',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('product_variants', 'size',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('product_variants', 'reorder_level')
    op.drop_column('product_variants', 'stock')
    # ### end Alembic commands ###
